{% set name = "kfp-server-api" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e2b28ba30481e4c6a980a555514cc074d752b6a4119371118265ecda946c1e7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - urllib3 >=1.25.8
    - six >=1.14.0
    - certifi
    - python-dateutil

test:
  imports:
    - kfp_server_api

about:
  home: https://github.com/kubeflow/pipelines
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: KF Pipelines API
  description: Generated python client for the KF Pipelines server API

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - tanguycdls
    - radcheb
