{% set name = "kfp-server-api" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a0f86d804647d4a526b42f3a04529324b0d50cba50e32e6706f950554adbb3e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5.3
    - pip
  run:
    - python >=3.5.3
    - urllib3 >=1.25.8
    - six >=1.14.0
    - certifi
    - python-dateutil

test:
  imports:
    - kfp_server_api

about:
  home: https://github.com/kubeflow/pipelines
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: KF Pipelines API
  description: Generated python client for the KF Pipelines server API

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - tanguycdls
    - radcheb
