{% set name = "kfp-server-api" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 702bb940eb77146f7c6430a4b938b99c99aadf6cdb25f59a4f5c2c193d9c1208

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - urllib3 >=1.15
    - six >=1.10
    - certifi
    - python-dateutil

test:
  imports:
    - kfp_server_api

about:
  home: https://github.com/kubeflow/pipelines
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: KF Pipelines API
  description: Generated python client for the KF Pipelines server API

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
