{% set name = "kfp-server-api" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e74df3cf5c999033b264c0587cdd26c1a30297820bca171c6dda2aa482b20392

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - urllib3 >=1.15
    - six >=1.10
    - certifi
    - python-dateutil

test:
  imports:
    - kfp_server_api

about:
  home: https://github.com/kubeflow/pipelines
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: KF Pipelines API
  description: Generated python client for the KF Pipelines server API

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - tanguycdls
    - radcheb
