travis:
  secure:
    BINSTAR_TOKEN: ce14zxPWFIugjhSIgpKLMTuib/d7RqwyGuIGbdHSzWfpzXn1R3eJO8EMYxsRCHpry/nx7WgykufdKI/4z8Nwf6n/S1GxJequ/23lJWKrjw+USSZV9bhtIQuA9d1N15WM4Bbtof6Cu2O5bbO++0014A8alkbWFhkYekkYrXjMmKK4FrJh2aUtb6wAoSuFKatSE+Dhx/c2xAQXlVzBJRcr/hqhpqBMriYS5XEf97e0V0vQRqibK34FXFRxjDQ/QYj4Vwtzahz4KzQPPJIWtGGcdREIHTYKKyOQTQ4WQb+nWiLTSiFfshFWnqQ9fHwQ8gSXU+W8BRiSQnUXrmL2KHrhafhmkVsI4DbNiesjxyQW5aqO9MSr2JFyJ5KHaIapPsoFtoyeWFa2+2kOogRChldusPQUFLmUOfyAGDKmqK0oAUMA9RoVIcAAFnu0A5WmXTkNNfjxNv2tbcM4qbFd6z3faENX7wwK/Grn4vmBK5b2tRJ2nyByLDMlR9KUDV13m7CZ9wU3Qgh9RJKPX+uCuSn7ViZFVQN1nGYRCGWicIX3e9WN6baExr4nOwv/Fdd/FvKbFNtXmDBDjoiHm5xF2voD6Rqd7N2qkuMHtHzfzF6/i188pXxsSCO7w/derdUERDnaDlen7StKcjB/LrNf/mPadbr8qioLHYO6YLXV+UoUlmw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
