travis:
  secure:
    BINSTAR_TOKEN: TccGHho3bztegjejA3dNFpcJB8RP/u274ioiIO5gSNgTG2XBjM3GGg0wZ/mA7tUp/f1AGKNtC7r/0nMdjtJIyZAZUYEwcuf2+LXoGARQj9OJVDM8EbSESN1Irzkr5HqizAoUueKv7qq43lnvG4pBlJP221wtdg9BiJG1/i6Vu7upg3A8SSgPnNxNmq9x3NvPL9RGfCmcvEfrq2nSzd0NZaR2qvI8orme7oJJ2lln6amhRRr08IZvY47/luQVA4pO9LRCtOA9l/nhngy7QS1R2huELfg6I+8P8n8zIPYLn9vX+p2wkHazWo1y0IgwDZCiu4xPwJfPbxDcK5uYjmb0lYDynJC++fGbJN1DT9lO+jBJiTQ5kESwC6bs8OGSTjIHgQRxPgGAQRcmu/D4TS+YdCMfE0L/tIrCxuPRuR6PzZWPv7SWaIXr5B7vP3zoztEBx/ObJaFtIlh1RrQ1K3F8FNJgFAGWQqKk0VqTNzrB0jihOsS9m8DnTOHu+6JZ7vRHoioNVGK0AJ38B8vVFsYWp5GqL5utQ9EA693vbfW8Co1szARRcnnO9IkfYRS18mzQOWV0YLN7wxPZROFOAY9fuYLa0QLU54UzwwOGCXhjDAXx1XOZZVl0f+4O4UELJKhV/mgTQavRNatHyJaYvNC8b8gWnyHuZR9hTBYtG8y3+2E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
